segmentation:
  experiment: 1
  batch_size: 32
  dataset_path: "..\\data\\lfw"
  load_checkpoint: null
  save_checkpoints_path: "..\\saved_models"
  plots_path: "..\\plots"
demo:
  model_path: "..\\saved_models\\model_bin_id1.pt"